name: Development Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python -m pytest tests/test_app.py tests/test_todo.py -v
    
    - name: Run code formatting check
      run: |
        python -m black --check app tests
    
    - name: Run linting
      run: |
        python -m flake8 app tests --max-line-length=88
        python -m pylint app tests --disable=C0114,C0116
    
    - name: Generate coverage report
      run: |
        python -m coverage run -m pytest tests/test_app.py tests/test_todo.py
        python -m coverage report
        python -m coverage xml
